import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { getCourses } from '../lib/prisma';
import styles from '../styles/Home.module.css';

export default function Home({ courses }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {courses && (
          <div>
            <h1>Courses</h1>
            <pre>{JSON.stringify(courses, null, 2)}</pre>
          </div>
        )}
        {!courses && (
          <div>
            <h1>no title</h1>
          </div>
        )}
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const data = await getCourses(true);

  return {
    props: {
      courses: JSON.parse(JSON.stringify(data)),
    },
  };
};
